### ISSUE TITLE
Improve Your Documentation

### ISSUE THREAD

**Issue by DriftedHawk49** [safiyat/sim8085#1]
## Please Improve Your Documentation
Please include How to use your files so that they can be further used if someone needs it.

**Comment by safiyat** [comment]
@DriftedHawk49 Hi! Thanks for dropping by.

This project was created using Qt Creator 2.7.2 on Linux in 2013. I have completely forgotten what most of the code does but you are welcome to use it, enhance it and ask me any pointed questions you might have.

I see you are complaining about documentation, but like I said, I have forgotten most of the code so it will take some time before I can understand it and write any documentation. You are welcome to do it if you feel like. I will probably forego the documentation part myself, but I am here to answer all your queries.

Cheers!
